# Generated by Django 4.2 on 2023-04-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='students',
            field=models.ManyToManyField(to='user.student'),
        ),
    ]
