# Generated by Django 4.2 on 2023-04-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_mentor_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='students',
        ),
    ]
